ssh_user: marcus
ssh_pw: geheim
ssh_server: home.server.com

smtp_server: smtp.mailserver.com
smtp_port: 25
smtp_host: localhost
smtp_user: admin@server.com
smtp_pw: geheim

email_from: admin@server.com
email_to: user@server.com